parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/UserManagement/Infrastructure/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    PhpAmqpLib\Connection\AMQPStreamConnection:
        arguments:
            $host: '%env(RABBITMQ_HOST)%'
            $port: '%env(RABBITMQ_PORT)%'
            $user: '%env(RABBITMQ_USER)%'
            $password: '%env(RABBITMQ_PASSWORD)%'

    App\EnvelopeManagement\Application\Handlers\CommandHandlers\CreateEnvelopeCommandHandler:
        tags: [ 'messenger.message_handler' ]

    App\EnvelopeManagement\Application\Handlers\CommandHandlers\NameEnvelopeCommandHandler:
        tags: [ 'messenger.message_handler' ]

    App\EnvelopeManagement\Application\Handlers\CommandHandlers\CreditEnvelopeCommandHandler:
        tags: [ 'messenger.message_handler' ]

    App\EnvelopeManagement\Application\Handlers\CommandHandlers\DebitEnvelopeCommandHandler:
        tags: [ 'messenger.message_handler' ]

    App\EnvelopeManagement\Application\Handlers\CommandHandlers\DeleteEnvelopeCommandHandler:
        tags: [ 'messenger.message_handler' ]

    App\EnvelopeManagement\Application\Handlers\QueryHandlers\ShowEnvelopeQueryHandler:
        tags: [ 'messenger.message_handler' ]

    App\EnvelopeManagement\Application\Handlers\QueryHandlers\ListEnvelopesQueryHandler:
        tags: [ 'messenger.message_handler' ]

    App\EnvelopeManagement\Application\Handlers\QueryHandlers\GetEnvelopeByTitleQueryHandler:
        tags: [ 'messenger.message_handler' ]

    App\EnvelopeManagement\ReadModels\Projections\EnvelopeCreatedProjection:
        tags: [ 'messenger.message_handler' ]

    App\EnvelopeManagement\ReadModels\Projections\EnvelopeNamedProjection:
        tags: [ 'messenger.message_handler' ]

    App\EnvelopeManagement\ReadModels\Projections\EnvelopeDebitedProjection:
        tags: [ 'messenger.message_handler' ]

    App\EnvelopeManagement\ReadModels\Projections\EnvelopeCreditedProjection:
        tags: [ 'messenger.message_handler' ]

    App\EnvelopeManagement\ReadModels\Projections\EnvelopeDeletedProjection:
        tags: [ 'messenger.message_handler' ]

    App\UserManagement\Application\Handlers\CommandHandlers\CreateUserCommandHandler:
        tags: [ 'messenger.message_handler' ]

    App\UserManagement\Application\Handlers\CommandHandlers\UpdateUserFirstnameCommandHandler:
        tags: [ 'messenger.message_handler' ]

    App\UserManagement\Application\Handlers\CommandHandlers\UpdateUserLastnameCommandHandler:
        tags: [ 'messenger.message_handler' ]

    App\UserManagement\Application\Handlers\CommandHandlers\UpdateUserPasswordCommandHandler:
        tags: [ 'messenger.message_handler' ]

    App\UserManagement\Application\Handlers\CommandHandlers\RequestUserPasswordResetCommandHandler:
        tags: [ 'messenger.message_handler' ]

    App\UserManagement\Application\Handlers\CommandHandlers\ResetUserPasswordCommandHandler:
        tags: [ 'messenger.message_handler' ]

    App\UserManagement\ReadModels\Projections\UserCreatedProjection:
        tags: [ 'messenger.message_handler' ]

    App\UserManagement\ReadModels\Projections\UserFirstnameUpdatedProjection:
        tags: [ 'messenger.message_handler' ]

    App\UserManagement\ReadModels\Projections\UserLastnameUpdatedProjection:
        tags: [ 'messenger.message_handler' ]

    App\UserManagement\ReadModels\Projections\UserPasswordResetRequestedProjection:
        tags: [ 'messenger.message_handler' ]

    App\UserManagement\ReadModels\Projections\UserPasswordUpdatedProjection:
        tags: [ 'messenger.message_handler' ]

    App\UserManagement\ReadModels\Projections\UserPasswordResetProjection:
        tags: [ 'messenger.message_handler' ]

    Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface:
        alias: 'security.password_hasher'

    App\SharedContext\Infrastructure\EventListener\ExceptionListener:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.exception' }
