framework:
    messenger:
        default_bus: command_bus
        buses:
            command_bus:
                default_middleware: true
                middleware:
                    - validation
            event_bus:
                default_middleware: true
                middleware:
                    - validation

        transports:
            sync: 'sync://'
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: messenger.transport.symfony_serializer
                options:
                    exchange:
                        name: 'domain_events'
                        type: fanout

        routing:
            'App\EnvelopeManagement\Domain\Events\EnvelopeCreatedEvent': async
            'App\EnvelopeManagement\Domain\Events\EnvelopeNamedEvent': async
            'App\EnvelopeManagement\Domain\Events\EnvelopeDebitedEvent': async
            'App\EnvelopeManagement\Domain\Events\EnvelopeDeletedEvent': async
            'App\EnvelopeManagement\Domain\Events\EnvelopeCreditedEvent': async
            'App\UserManagement\Domain\Events\UserCreatedEvent': async
            'App\UserManagement\Domain\Events\UserFirstnameUpdatedEvent': async
            'App\UserManagement\Domain\Events\UserLastnameUpdatedEvent': async

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
